### PR TITLE
Use Ruby 2.2.3

### PR DESCRIPTION
**Pull request by masutaka**
I want to use the latest ruby :smirk_cat:

### CODE REVIEW

**Comment by june29** [comment]
Oh thank you! Sorry for my laziness... I'll merge!

**Comment by masutaka** [comment]
:+1:

**Comment by june29** [comment]
And I started to using 29hours with Ruby 2.2.3 now.
At this moment, it works without problem :+1:

**Comment by masutaka** [comment]
Also I use Ruby 2.2.3 in https://github.com/masutaka/masutaka-29hours :smile:

**Pull request merged**
